/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.genomics.model;

/**
 * A Callset is a collection of Variant Calls. It belongs to a Dataset.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Genomics API. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 */
@SuppressWarnings("javadoc")
public final class Callset extends com.google.api.client.json.GenericJson {

  /**
   * The date this callset was created in milliseconds from the epoch.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long created;

  /**
   * The ID of the dataset this callset belongs to.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String datasetId;

  /**
   * The callset ID.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * A map of additional callset information.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.Map<String, java.util.List<java.lang.String>> info;

  /**
   * The callset name.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The date this callset was created in milliseconds from the epoch.
   * @return value or {@code null} for none
   */
  public java.lang.Long getCreated() {
    return created;
  }

  /**
   * The date this callset was created in milliseconds from the epoch.
   * @param created created or {@code null} for none
   */
  public Callset setCreated(java.lang.Long created) {
    this.created = created;
    return this;
  }

  /**
   * The ID of the dataset this callset belongs to.
   * @return value or {@code null} for none
   */
  public java.lang.String getDatasetId() {
    return datasetId;
  }

  /**
   * The ID of the dataset this callset belongs to.
   * @param datasetId datasetId or {@code null} for none
   */
  public Callset setDatasetId(java.lang.String datasetId) {
    this.datasetId = datasetId;
    return this;
  }

  /**
   * The callset ID.
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * The callset ID.
   * @param id id or {@code null} for none
   */
  public Callset setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * A map of additional callset information.
   * @return value or {@code null} for none
   */
  public java.util.Map<String, java.util.List<java.lang.String>> getInfo() {
    return info;
  }

  /**
   * A map of additional callset information.
   * @param info info or {@code null} for none
   */
  public Callset setInfo(java.util.Map<String, java.util.List<java.lang.String>> info) {
    this.info = info;
    return this;
  }

  /**
   * The callset name.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * The callset name.
   * @param name name or {@code null} for none
   */
  public Callset setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  @Override
  public Callset set(String fieldName, Object value) {
    return (Callset) super.set(fieldName, value);
  }

  @Override
  public Callset clone() {
    return (Callset) super.clone();
  }

}
