/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.genomics.model;

/**
 * The readset export request.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Genomics API. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 */
@SuppressWarnings("javadoc")
public final class ExportReadsetsRequest extends com.google.api.client.json.GenericJson {

  /**
   * A Google Cloud Storage URI where the exported BAM file will be created.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String exportUri;

  /**
   * The Google Cloud project number that owns this export. This is the project that will be billed.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long projectId;

  /**
   * The IDs of the readsets to export.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> readsetIds;

  /**
   * A Google Cloud Storage URI where the exported BAM file will be created.
   * @return value or {@code null} for none
   */
  public java.lang.String getExportUri() {
    return exportUri;
  }

  /**
   * A Google Cloud Storage URI where the exported BAM file will be created.
   * @param exportUri exportUri or {@code null} for none
   */
  public ExportReadsetsRequest setExportUri(java.lang.String exportUri) {
    this.exportUri = exportUri;
    return this;
  }

  /**
   * The Google Cloud project number that owns this export. This is the project that will be billed.
   * @return value or {@code null} for none
   */
  public java.lang.Long getProjectId() {
    return projectId;
  }

  /**
   * The Google Cloud project number that owns this export. This is the project that will be billed.
   * @param projectId projectId or {@code null} for none
   */
  public ExportReadsetsRequest setProjectId(java.lang.Long projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * The IDs of the readsets to export.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getReadsetIds() {
    return readsetIds;
  }

  /**
   * The IDs of the readsets to export.
   * @param readsetIds readsetIds or {@code null} for none
   */
  public ExportReadsetsRequest setReadsetIds(java.util.List<java.lang.String> readsetIds) {
    this.readsetIds = readsetIds;
    return this;
  }

  @Override
  public ExportReadsetsRequest set(String fieldName, Object value) {
    return (ExportReadsetsRequest) super.set(fieldName, value);
  }

  @Override
  public ExportReadsetsRequest clone() {
    return (ExportReadsetsRequest) super.clone();
  }

}
