/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.genomics.model;

/**
 * Model definition for Header.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Genomics API. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 */
@SuppressWarnings("javadoc")
public final class Header extends com.google.api.client.json.GenericJson {

  /**
   * (SO) Sorting order of alignments.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String sortingOrder;

  /**
   * (VN) BAM format version.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String version;

  /**
   * (SO) Sorting order of alignments.
   * @return value or {@code null} for none
   */
  public java.lang.String getSortingOrder() {
    return sortingOrder;
  }

  /**
   * (SO) Sorting order of alignments.
   * @param sortingOrder sortingOrder or {@code null} for none
   */
  public Header setSortingOrder(java.lang.String sortingOrder) {
    this.sortingOrder = sortingOrder;
    return this;
  }

  /**
   * (VN) BAM format version.
   * @return value or {@code null} for none
   */
  public java.lang.String getVersion() {
    return version;
  }

  /**
   * (VN) BAM format version.
   * @param version version or {@code null} for none
   */
  public Header setVersion(java.lang.String version) {
    this.version = version;
    return this;
  }

  @Override
  public Header set(String fieldName, Object value) {
    return (Header) super.set(fieldName, value);
  }

  @Override
  public Header clone() {
    return (Header) super.clone();
  }

}
