/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.genomics.model;

/**
 * Model definition for ReferenceSequence.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Genomics API. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 */
@SuppressWarnings("javadoc")
public final class ReferenceSequence extends com.google.api.client.json.GenericJson {

  /**
   * (AS) Genome assembly identifier.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String assemblyId;

  /**
   * (LN) Reference sequence length.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer length;

  /**
   * (M5) MD5 checksum of the sequence in the uppercase, excluding spaces but including pads as *.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String md5Checksum;

  /**
   * (SN) Reference sequence name.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * (SP) Species.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String species;

  /**
   * (UR) URI of the sequence.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String uri;

  /**
   * (AS) Genome assembly identifier.
   * @return value or {@code null} for none
   */
  public java.lang.String getAssemblyId() {
    return assemblyId;
  }

  /**
   * (AS) Genome assembly identifier.
   * @param assemblyId assemblyId or {@code null} for none
   */
  public ReferenceSequence setAssemblyId(java.lang.String assemblyId) {
    this.assemblyId = assemblyId;
    return this;
  }

  /**
   * (LN) Reference sequence length.
   * @return value or {@code null} for none
   */
  public java.lang.Integer getLength() {
    return length;
  }

  /**
   * (LN) Reference sequence length.
   * @param length length or {@code null} for none
   */
  public ReferenceSequence setLength(java.lang.Integer length) {
    this.length = length;
    return this;
  }

  /**
   * (M5) MD5 checksum of the sequence in the uppercase, excluding spaces but including pads as *.
   * @return value or {@code null} for none
   */
  public java.lang.String getMd5Checksum() {
    return md5Checksum;
  }

  /**
   * (M5) MD5 checksum of the sequence in the uppercase, excluding spaces but including pads as *.
   * @param md5Checksum md5Checksum or {@code null} for none
   */
  public ReferenceSequence setMd5Checksum(java.lang.String md5Checksum) {
    this.md5Checksum = md5Checksum;
    return this;
  }

  /**
   * (SN) Reference sequence name.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * (SN) Reference sequence name.
   * @param name name or {@code null} for none
   */
  public ReferenceSequence setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * (SP) Species.
   * @return value or {@code null} for none
   */
  public java.lang.String getSpecies() {
    return species;
  }

  /**
   * (SP) Species.
   * @param species species or {@code null} for none
   */
  public ReferenceSequence setSpecies(java.lang.String species) {
    this.species = species;
    return this;
  }

  /**
   * (UR) URI of the sequence.
   * @return value or {@code null} for none
   */
  public java.lang.String getUri() {
    return uri;
  }

  /**
   * (UR) URI of the sequence.
   * @param uri uri or {@code null} for none
   */
  public ReferenceSequence setUri(java.lang.String uri) {
    this.uri = uri;
    return this;
  }

  @Override
  public ReferenceSequence set(String fieldName, Object value) {
    return (ReferenceSequence) super.set(fieldName, value);
  }

  @Override
  public ReferenceSequence clone() {
    return (ReferenceSequence) super.clone();
  }

}
